DROP TABLE IF EXISTS tokens;

CREATE TABLE tokens (
    hash BYTEA PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expiry TIMESTAMPTZ(0) NOT NULL,
    scope TEXT NOT NULL
);
